services:
  - type: web
    name: octopus-moba
    runtime: docker
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
    healthCheckPath: /
